# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 02:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
