# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20170817_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
